services:
  decryption-manager-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: canvassr/decryption-manager:dev
    stdin_open: true
    tty: true
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/data
    environment:
      - CDM_DATA_DIR=/data
    command: decryption-manager
